<div id="mysubs">
    

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formsubs');
$form->setAttribute('action', $this->url('subs_'.$this->locale));
/*переопределим формат ошибок*/
echo $this->form()->openTag($form);
$formLabel = $this->plugin('formLabel');
foreach ($form as $k=>$item){
    $i=$form->get($k);
    $type=$item->getAttribute("type");

    $error=$i->getMessages();
    if (!empty($error)){$flagError=true;}
    if ($type=="submit"){
        $align=" text-right";
    } else {
        $align="";
    }
    if ($type=="hidden"){
        echo $this->FormHidden($i);
    } else {

        ?>
        <div class="form-group<?=$align?>">
        <?php 
        $item->setAttribute("class","form-control form-control-sm");
        switch ($type){
            case "select":{
                echo $this->formLabel($i).$this->FormSelect($i);
                break;
            }
            case "multi_checkbox":{
                $m=$this->FormMultiCheckbox();
                $m->setSeparator("<br/>");
                echo $this->formLabel($i).'<div class="form-check pt-2">'.$m->Render($i).'</div>';
                break;
            }
            case "checkbox":{
                echo $this->FormCheckbox($i).$this->formLabel($i);
                break;
            }
            case "submit":{
                $i->setAttributes(["class"=>"btn btn-primary"]);
                echo $this->FormSubmit($i);
                break;
            }

            default:{
                echo $this->formLabel($i).$this->formElement($i);
            }
        }
        ?>
        <?=(!empty($error)) ? '<div class="alert alert-danger" role="alert">'.implode("<br>",$error).'</div>':"" ?>
          </div>
        <?php
    }
}
echo $this->form()->closeTag();
    ?>

</div>
<script type="text/javascript">
$("#formsubs").on("submit",function(e){
    e.preventDefault();
    $(this).ajaxSubmit({target: '#mysubs'});
});

</script>
